credentials-file: /cloudflare/tunnel-credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
# XXX the internal ingress service should be injected, rather than hardcoded.
ingress:
  - service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
